### ISSUE TITLE
Database.KyotoCabinet.Foreign.KCREC.poke not implemented

### ISSUE THREAD

**Issue by bryanvick** [bitonic/kyotocabinet#4]
I attempted to use setBulk using a Tree database and ran into this error which happens at line 99 in Database.KyotoCabinet.Foreign.  I have no experience with Haskell's foreign function interface so I can't recommend a fix.

P.S. Thanks for the library, I'm excited to use it!

**Comment by Yuras** [comment]
I implemented it in #5. Could you please try it out.

**Comment by bryanvick** [comment]
It's working for me.  Thanks a bunch Yuras.

**Comment by Yuras** [comment]
Released on hackage as 0.1.4
